### ISSUE TITLE
Support for firefox

### ISSUE THREAD

**Issue by infothrill** [pawanmaurya/imdb-ratings-on-netflix#1]
It'd be great to support the last remaining competitor to chrome.

**Comment by pawanmaurya** [comment]
Sure, will work on it

**Comment by mavilam** [comment]
I just clone the repository, put my OMDB secret key and upload as temporary add on in Firefox and it works perfectly without any more change

**Comment by pawanmaurya** [comment]
@mavilam thanks for info, will make it for firefox, too, then.

**Comment by pawanmaurya** [comment]
Submitted firefox add-on for review.
Link : https://addons.mozilla.org/en-US/firefox/addon/imdb-ratings-on-netflix/
